### ISSUE TITLE
Please author answer what is the reason for this?

### ISSUE THREAD

**Issue by Lyra1122** [lazatsoc/cbis_ddsm_dataloader#3]
Found 0 dcm images to convert. Skipped 0.
Found 0 dcm images to convert. Skipped 0.
Processing 2 abnormality csv files for training.
100%|██████████| 2864/2864 [00:00<00:00, 3539.14abnormalities/s]
Processing 2 abnormality csv files for testing.
100%|██████████| 704/704 [00:00<00:00, 3683.98abnormalities/s]
Could not locate 3568 files. Please re-run the downloader.
![Uploading 微信图片_20240624185514.png…]()

**Comment by lazatsoc** [comment]
This is related to the #2 . Images are not being downloaded so the preprocessor cannot find them.
